### PR TITLE
add drug help part 1

### PR DESCRIPTION
**Pull request by polivilas**

### CODE REVIEW

**Comment by CaveeJohnson** [comment]
https://github.com/CaveeJohnson/BaseWars-new/blob/master/basewars/gamemode/config.lua#L17
:book: :eyes:

**Comment by polivilas** [comment]
i highly doubt newfags will look up the git and read the code just to see what the drugs do

**Comment by CaveeJohnson** [comment]
I was talking to you, there is allready a Config.Drugs table, you are overwriting it's namespace...

**Comment by polivilas** [comment]
oh

**Comment by CaveeJohnson** [comment]
:+1:

**Pull request merged**
